### ISSUE TITLE
Translate the Contributing.md into English

### ISSUE THREAD

**Issue by M3lkior** [ineat/refcards#55]
The contributing file is today in french ; the idea is to provide an english version to be worldwide

**Comment by VishMaster17** [comment]
Hi @M3lkior, I would love to work on this. Can you please assign this to me.

**Comment by GuigzC** [comment]
Hi, can I work on this project, please ?

**Comment by GuigzC** [comment]
From Ineat @M3lkior

**Comment by M3lkior** [comment]
ok @GuigzC  !

@VishMaster17 if you want i create others translations issues on our refcards

**Comment by M3lkior** [comment]
Close by #62
