### ISSUE TITLE
Translate the Git refcard into English

### ISSUE THREAD

**Issue by M3lkior** [ineat/refcards#57]
Translate the Git refcard into English

**Comment by FaithKovi** [comment]
Hello @M3lkior I will like to work on this issue

**Comment by FaithKovi** [comment]
Where is the Git refcard located?

**Comment by M3lkior** [comment]
hey ; ok let do this ! 

Be careful to preserve the Markdown syntax ;)

**Comment by M3lkior** [comment]
> Hello @M3lkior I will like to work on this issue

the FR file is here: https://github.com/ineat/refcards/blob/master/git/FR.md

the naming convention of the EN file should be `EN.md` in the same git folder

**Comment by FaithKovi** [comment]
@M3lkior I made a pull request for this issue. Please review

**Comment by M3lkior** [comment]
Closed by #60
